#define BLE_GATT_UUID_NAMESPACE_BLUETOOTH_SIG 0x01
#define BLE_GATT_UUID_NAMESPACE_NONE 0x00

#define BLE_GATT_UUID_UNIT_TIME_SECONDS 				0x2703
#define BLE_GATT_UUID_UNIT_TEMPERATURE_CELSIUS 			0x272F
#define BLE_GATT_UUID_UNIT_UNITLESS 					0x2700
#define BLE_GATT_UUID_UNIT_PRESSURE_MMHG 				0x2781
#define BLE_GATT_UUID_UNIT_PERCENTAGE					0x27AD
#define BLE_GATT_UUID_UNIT_RESISTANCE_OHM				0x272A
#define BLE_GATT_UUID_UNIT_CONCENTRATION_PPM			0x27C4
